# Generated by Django 4.1 on 2023-03-02 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_medicine_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryPaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('medicines', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.medicine', verbose_name='Medicine')),
            ],
        ),
    ]
