# Generated by Django 4.1 on 2023-03-02 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_historypaid_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historypaid',
            name='total_amount',
        ),
    ]
