# Generated by Django 4.1 on 2023-03-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_historypaid_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phn_no',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lname',
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
