# Generated by Django 4.1 on 2023-03-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_phn_no_customer_phone_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historypaid',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
    ]
